version: "3"

services:
  weatherapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - ./weatherApp:/weatherApp
    command: >
      sh -c "python manage.py runserver 127.0.0.1:8000"